[package]
name = "hello-world"
version = "0.1.0"
authors = ["Christopher Hunt"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"

[dependencies.nrf9160-hal]
features = ["rt"]
path = "../../nrf9160-hal"
optional = true

[dependencies.nrf9120-hal]
features = ["rt"]
path = "../../nrf9120-hal"
optional = true

[dependencies.nrf52840-hal]
features = ["rt"]
path = "../../nrf52840-hal"
optional = true

[features]
9160 = ["nrf9160-hal"]
9120 = ["nrf9120-hal"]
52840 = ["nrf52840-hal"]
